//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class ApprovalMatrix
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Content Content2;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.HiddenField hfWorkflowStepId;
    protected global::System.Web.UI.WebControls.DropDownList ddlEntityType;
    protected global::System.Web.UI.WebControls.TextBox txtStepCode;
    protected global::System.Web.UI.WebControls.TextBox txtStepNameAr;
    protected global::System.Web.UI.WebControls.TextBox txtStepNameEn;
    protected global::System.Web.UI.WebControls.TextBox txtRequiredPermission;
    protected global::System.Web.UI.WebControls.TextBox txtSortOrder;
    protected global::System.Web.UI.WebControls.CheckBox chkIsFinal;
    protected global::System.Web.UI.WebControls.CheckBox chkIsActive;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.Button btnClear;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterEntityType;
    protected global::System.Web.UI.WebControls.Button btnFilter;
    protected global::System.Web.UI.WebControls.GridView gvSteps;
}
