//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by GeoSite Pro Sprint 5 tooling.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class AuditLog
{
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    protected global::System.Web.UI.WebControls.TextBox txtActionType;
    protected global::System.Web.UI.WebControls.TextBox txtEntityName;
    protected global::System.Web.UI.WebControls.DropDownList ddlUser;
    protected global::System.Web.UI.WebControls.TextBox txtDateFrom;
    protected global::System.Web.UI.WebControls.TextBox txtDateTo;
    protected global::System.Web.UI.WebControls.Button btnSearch;
    protected global::System.Web.UI.WebControls.Button btnClearSearch;
    protected global::System.Web.UI.WebControls.GridView gvAuditLog;
}
