//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class BackupCenter
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Content Content2;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.DropDownList ddlBackupType;
    protected global::System.Web.UI.WebControls.TextBox txtBackupPath;
    protected global::System.Web.UI.WebControls.TextBox txtDescription;
    protected global::System.Web.UI.WebControls.Button btnCreateBackupRequest;
    protected global::System.Web.UI.WebControls.Button btnGenerateCommand;
    protected global::System.Web.UI.WebControls.Panel pnlCommand;
    protected global::System.Web.UI.WebControls.Literal litBackupCommand;
    protected global::System.Web.UI.WebControls.GridView gvBackupJobs;
}
