//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class BoreholeLog
{
    protected global::System.Web.UI.WebControls.Button btnNewLayer;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.DropDownList ddlProject;
    protected global::System.Web.UI.WebControls.DropDownList ddlBorehole;
    protected global::System.Web.UI.WebControls.Panel pnlHeader;
    protected global::System.Web.UI.WebControls.Literal litBoreholeCode;
    protected global::System.Web.UI.WebControls.Literal litProject;
    protected global::System.Web.UI.WebControls.Literal litActualDepth;
    protected global::System.Web.UI.WebControls.Literal litDrillingMethod;
    protected global::System.Web.UI.WebControls.Literal litElevation;
    protected global::System.Web.UI.WebControls.Literal litGroundwater;
    protected global::System.Web.UI.WebControls.HyperLink lnkBoreholeEdit;
    protected global::System.Web.UI.WebControls.HyperLink lnkSamples;
    protected global::System.Web.UI.WebControls.HyperLink lnkSPT;
    protected global::System.Web.UI.WebControls.HyperLink lnkGroundwater;
    protected global::System.Web.UI.WebControls.Panel pnlLayerForm;
    protected global::System.Web.UI.WebControls.Literal litLayerFormTitle;
    protected global::System.Web.UI.WebControls.HiddenField hfLayerId;
    protected global::System.Web.UI.WebControls.TextBox txtFromDepthM;
    protected global::System.Web.UI.WebControls.TextBox txtToDepthM;
    protected global::System.Web.UI.WebControls.DropDownList ddlSoilRockType;
    protected global::System.Web.UI.WebControls.TextBox txtUSCS;
    protected global::System.Web.UI.WebControls.TextBox txtColor;
    protected global::System.Web.UI.WebControls.TextBox txtConsistencyDensity;
    protected global::System.Web.UI.WebControls.TextBox txtMoistureCondition;
    protected global::System.Web.UI.WebControls.TextBox txtRecoveryPercent;
    protected global::System.Web.UI.WebControls.TextBox txtRQDPercent;
    protected global::System.Web.UI.WebControls.TextBox txtDescription;
    protected global::System.Web.UI.WebControls.TextBox txtNotes;
    protected global::System.Web.UI.WebControls.Button btnSaveLayer;
    protected global::System.Web.UI.WebControls.Button btnCancelLayer;
    protected global::System.Web.UI.WebControls.GridView gvLayers;
    protected global::System.Web.UI.WebControls.GridView gvSamples;
    protected global::System.Web.UI.WebControls.GridView gvSPT;
    protected global::System.Web.UI.WebControls.GridView gvGroundwater;
}
