//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Boreholes
{
    protected global::System.Web.UI.WebControls.Button btnNew;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjects;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.Panel pnlForm;
    protected global::System.Web.UI.WebControls.Literal litFormTitle;
    protected global::System.Web.UI.WebControls.HiddenField hfBoreholeId;
    protected global::System.Web.UI.WebControls.DropDownList ddlProject;
    protected global::System.Web.UI.WebControls.TextBox txtBoreholeCode;
    protected global::System.Web.UI.WebControls.TextBox txtPlannedDepthM;
    protected global::System.Web.UI.WebControls.TextBox txtActualDepthM;
    protected global::System.Web.UI.WebControls.TextBox txtEasting;
    protected global::System.Web.UI.WebControls.TextBox txtNorthing;
    protected global::System.Web.UI.WebControls.TextBox txtElevationM;
    protected global::System.Web.UI.WebControls.DropDownList ddlDrillingMethod;
    protected global::System.Web.UI.WebControls.DropDownList ddlBoreholeStatus;
    protected global::System.Web.UI.WebControls.TextBox txtGroundwaterDepthM;
    protected global::System.Web.UI.WebControls.TextBox txtStartDate;
    protected global::System.Web.UI.WebControls.TextBox txtEndDate;
    protected global::System.Web.UI.WebControls.TextBox txtFieldEngineer;
    protected global::System.Web.UI.WebControls.CheckBox chkIsActive;
    protected global::System.Web.UI.WebControls.TextBox txtLocationDescription;
    protected global::System.Web.UI.WebControls.TextBox txtTerminationReason;
    protected global::System.Web.UI.WebControls.TextBox txtNotes;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.Button btnCancel;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterProject;
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    protected global::System.Web.UI.WebControls.Button btnSearch;
    protected global::System.Web.UI.WebControls.Button btnClearSearch;
    protected global::System.Web.UI.WebControls.GridView gvBoreholes;
}
