//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class CrossSections
{
    protected global::System.Web.UI.WebControls.HyperLink lnkSiteMap;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.DropDownList ddlProject;
    protected global::System.Web.UI.WebControls.Button btnLoad;
    protected global::System.Web.UI.WebControls.Panel pnlProject;
    protected global::System.Web.UI.WebControls.Literal litProjectTitle;
    protected global::System.Web.UI.WebControls.Literal litProjectMeta;
    protected global::System.Web.UI.WebControls.Panel pnlForm;
    protected global::System.Web.UI.WebControls.HiddenField hfSectionId;
    protected global::System.Web.UI.WebControls.TextBox txtSectionCode;
    protected global::System.Web.UI.WebControls.TextBox txtSectionName;
    protected global::System.Web.UI.WebControls.DropDownList ddlBaselineType;
    protected global::System.Web.UI.WebControls.DropDownList ddlSectionStatus;
    protected global::System.Web.UI.WebControls.TextBox txtHorizontalScale;
    protected global::System.Web.UI.WebControls.TextBox txtVerticalScale;
    protected global::System.Web.UI.WebControls.TextBox txtStartEasting;
    protected global::System.Web.UI.WebControls.TextBox txtStartNorthing;
    protected global::System.Web.UI.WebControls.TextBox txtEndEasting;
    protected global::System.Web.UI.WebControls.TextBox txtEndNorthing;
    protected global::System.Web.UI.WebControls.TextBox txtNotes;
    protected global::System.Web.UI.WebControls.Button btnSaveSection;
    protected global::System.Web.UI.WebControls.Button btnGenerateBoreholes;
    protected global::System.Web.UI.WebControls.Button btnClear;
    protected global::System.Web.UI.WebControls.Panel pnlSections;
    protected global::System.Web.UI.WebControls.GridView gvSections;
    protected global::System.Web.UI.WebControls.Panel pnlSectionView;
    protected global::System.Web.UI.WebControls.Literal litSectionTitle;
    protected global::System.Web.UI.WebControls.Literal litSectionMeta;
    protected global::System.Web.UI.WebControls.Button btnRefreshSection;
    protected global::System.Web.UI.WebControls.Literal litSectionSvg;
    protected global::System.Web.UI.WebControls.GridView gvSectionBoreholes;
}
