//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
//     Changes to this file may be overwritten by Visual Studio.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Dashboard
{
    protected global::System.Web.UI.WebControls.Content Content1;

    protected global::System.Web.UI.WebControls.Content Content2;

    protected global::System.Web.UI.WebControls.HyperLink lnkNewProject;

    protected global::System.Web.UI.WebControls.HyperLink lnkProjects;

    protected global::System.Web.UI.WebControls.Panel pnlMessage;

    protected global::System.Web.UI.WebControls.Literal litMessage;

    protected global::System.Web.UI.WebControls.Literal litTotalProjects;

    protected global::System.Web.UI.WebControls.Literal litActiveProjects;

    protected global::System.Web.UI.WebControls.Literal litTotalBoreholes;

    protected global::System.Web.UI.WebControls.Literal litTotalLabTests;
    protected global::System.Web.UI.WebControls.Literal litTotalReports;

    protected global::System.Web.UI.WebControls.GridView gvRecentProjects;

    protected global::System.Web.UI.WebControls.GridView gvProjectStatus;

}
