//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class DataExchange
{
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.DropDownList ddlProject;
    protected global::System.Web.UI.WebControls.Button btnRefresh;
    protected global::System.Web.UI.WebControls.Panel pnlProject;
    protected global::System.Web.UI.WebControls.Literal litOverview;
    protected global::System.Web.UI.WebControls.HyperLink lnkExportBoreholes;
    protected global::System.Web.UI.WebControls.HyperLink lnkExportLayers;
    protected global::System.Web.UI.WebControls.HyperLink lnkExportSamples;
    protected global::System.Web.UI.WebControls.HyperLink lnkExportSPT;
    protected global::System.Web.UI.WebControls.HyperLink lnkExportGroundwater;
    protected global::System.Web.UI.WebControls.HyperLink lnkExportLab;
    protected global::System.Web.UI.WebControls.HyperLink lnkExportReports;
    protected global::System.Web.UI.WebControls.GridView gvHistory;
}
