//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class ExecutiveDashboard
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Content Content2;
    protected global::System.Web.UI.WebControls.Button btnRefresh;
    protected global::System.Web.UI.WebControls.HyperLink lnkRisks;
    protected global::System.Web.UI.WebControls.HyperLink lnkKpis;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.Literal litTotalProjects;
    protected global::System.Web.UI.WebControls.Literal litActiveProjects;
    protected global::System.Web.UI.WebControls.Literal litTotalBoreholes;
    protected global::System.Web.UI.WebControls.Literal litTotalLabResults;
    protected global::System.Web.UI.WebControls.Literal litPendingApprovals;
    protected global::System.Web.UI.WebControls.Literal litOverdueFollowUps;
    protected global::System.Web.UI.WebControls.Literal litHighRisks;
    protected global::System.Web.UI.WebControls.Literal litAverageQualityScore;
    protected global::System.Web.UI.WebControls.GridView gvTopRisks;
    protected global::System.Web.UI.WebControls.GridView gvQualityScores;
    protected global::System.Web.UI.WebControls.GridView gvAttention;
}
