//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class FollowUpBoard
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Content Content2;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.HiddenField hfFollowUpItemId;
    protected global::System.Web.UI.WebControls.DropDownList ddlProject;
    protected global::System.Web.UI.WebControls.DropDownList ddlRelatedEntityType;
    protected global::System.Web.UI.WebControls.TextBox txtTitle;
    protected global::System.Web.UI.WebControls.TextBox txtDescription;
    protected global::System.Web.UI.WebControls.TextBox txtDueDate;
    protected global::System.Web.UI.WebControls.DropDownList ddlPriority;
    protected global::System.Web.UI.WebControls.DropDownList ddlAssignedTo;
    protected global::System.Web.UI.WebControls.TextBox txtRelatedEntityId;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.Button btnClear;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterProject;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    protected global::System.Web.UI.WebControls.Button btnLoad;
    protected global::System.Web.UI.WebControls.GridView gvFollowUps;
}
