//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class GisCadExport
{
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.DropDownList ddlProject;
    protected global::System.Web.UI.WebControls.Button btnRefresh;
    protected global::System.Web.UI.WebControls.Panel pnlProject;
    protected global::System.Web.UI.WebControls.HyperLink lnkGisPoints;
    protected global::System.Web.UI.WebControls.HyperLink lnkGisLayers;
    protected global::System.Web.UI.WebControls.HyperLink lnkCadPoints;
    protected global::System.Web.UI.WebControls.HyperLink lnkCrossSectionLayers;
    protected global::System.Web.UI.WebControls.GridView gvPoints;
    protected global::System.Web.UI.WebControls.GridView gvSections;
}
