//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Groundwater
{
    protected global::System.Web.UI.WebControls.Button btnNew;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.Panel pnlForm;
    protected global::System.Web.UI.WebControls.Literal litFormTitle;
    protected global::System.Web.UI.WebControls.HiddenField hfGroundwaterObservationId;
    protected global::System.Web.UI.WebControls.DropDownList ddlProject;
    protected global::System.Web.UI.WebControls.DropDownList ddlBorehole;
    protected global::System.Web.UI.WebControls.TextBox txtObservationDate;
    protected global::System.Web.UI.WebControls.TextBox txtDepthToWaterM;
    protected global::System.Web.UI.WebControls.DropDownList ddlObservationType;
    protected global::System.Web.UI.WebControls.TextBox txtCasingDepthM;
    protected global::System.Web.UI.WebControls.TextBox txtStabilizedAfterHours;
    protected global::System.Web.UI.WebControls.TextBox txtNotes;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.Button btnCancel;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterProject;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterBorehole;
    protected global::System.Web.UI.WebControls.Button btnClearSearch;
    protected global::System.Web.UI.WebControls.GridView gvGroundwater;
}
