//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
//     Changes to this file may be overwritten by Visual Studio.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class LabResults
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Content Content2;
    protected global::System.Web.UI.WebControls.Button btnNew;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.Panel pnlForm;
    protected global::System.Web.UI.WebControls.Literal litFormTitle;
    protected global::System.Web.UI.WebControls.HiddenField hfLabTestResultId;
    protected global::System.Web.UI.WebControls.DropDownList ddlProject;
    protected global::System.Web.UI.WebControls.DropDownList ddlBorehole;
    protected global::System.Web.UI.WebControls.DropDownList ddlSample;
    protected global::System.Web.UI.WebControls.DropDownList ddlLabTestType;
    protected global::System.Web.UI.WebControls.TextBox txtTestCode;
    protected global::System.Web.UI.WebControls.TextBox txtTestStandard;
    protected global::System.Web.UI.WebControls.TextBox txtTestDate;
    protected global::System.Web.UI.WebControls.DropDownList ddlResultStatus;
    protected global::System.Web.UI.WebControls.TextBox txtNumericValue;
    protected global::System.Web.UI.WebControls.TextBox txtUnit;
    protected global::System.Web.UI.WebControls.TextBox txtResultValue;
    protected global::System.Web.UI.WebControls.TextBox txtTechnician;
    protected global::System.Web.UI.WebControls.TextBox txtReviewedBy;
    protected global::System.Web.UI.WebControls.CheckBox chkIsApproved;
    protected global::System.Web.UI.WebControls.TextBox txtResultText;
    protected global::System.Web.UI.WebControls.TextBox txtRemarks;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.Button btnCancel;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterProject;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterBorehole;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterSample;
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    protected global::System.Web.UI.WebControls.Button btnSearch;
    protected global::System.Web.UI.WebControls.Button btnClearSearch;
    protected global::System.Web.UI.WebControls.GridView gvLabResults;
}
