//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
//     Changes to this file may be overwritten by Visual Studio.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Login
{
    protected global::System.Web.UI.WebControls.Panel pnlMessage;

    protected global::System.Web.UI.WebControls.Literal litMessage;

    protected global::System.Web.UI.WebControls.TextBox txtUsername;

    protected global::System.Web.UI.WebControls.TextBox txtPassword;

    protected global::System.Web.UI.WebControls.Button btnLogin;

    protected global::System.Web.UI.HtmlControls.HtmlForm form1;

}
