//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Notifications
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Content Content2;
    protected global::System.Web.UI.WebControls.Button btnGenerate;
    protected global::System.Web.UI.WebControls.Button btnMarkAllRead;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
    protected global::System.Web.UI.WebControls.DropDownList ddlSeverity;
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    protected global::System.Web.UI.WebControls.Button btnLoad;
    protected global::System.Web.UI.WebControls.Literal litUnreadCount;
    protected global::System.Web.UI.WebControls.Literal litCriticalCount;
    protected global::System.Web.UI.WebControls.Literal litOverdueCount;
    protected global::System.Web.UI.WebControls.Literal litTotalCount;
    protected global::System.Web.UI.WebControls.GridView gvNotifications;
}
