//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class NotificationRules
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Content Content2;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.HiddenField hfNotificationRuleId;
    protected global::System.Web.UI.WebControls.TextBox txtRuleCode;
    protected global::System.Web.UI.WebControls.TextBox txtRuleNameAr;
    protected global::System.Web.UI.WebControls.DropDownList ddlRuleType;
    protected global::System.Web.UI.WebControls.DropDownList ddlEntityType;
    protected global::System.Web.UI.WebControls.TextBox txtDaysOffset;
    protected global::System.Web.UI.WebControls.DropDownList ddlSeverity;
    protected global::System.Web.UI.WebControls.TextBox txtMessageTemplate;
    protected global::System.Web.UI.WebControls.CheckBox chkIsActive;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.Button btnClear;
    protected global::System.Web.UI.WebControls.GridView gvRules;
}
