//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class OperationLogs
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Content Content2;
    protected global::System.Web.UI.WebControls.Button btnRefresh;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.DropDownList ddlLogLevel;
    protected global::System.Web.UI.WebControls.TextBox txtModule;
    protected global::System.Web.UI.WebControls.TextBox txtFromDate;
    protected global::System.Web.UI.WebControls.TextBox txtToDate;
    protected global::System.Web.UI.WebControls.Button btnSearch;
    protected global::System.Web.UI.WebControls.GridView gvOperationLogs;
}
