//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class ProjectApproval
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Content Content2;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.DropDownList ddlProject;
    protected global::System.Web.UI.WebControls.Button btnLoad;
    protected global::System.Web.UI.WebControls.Panel pnlProject;
    protected global::System.Web.UI.WebControls.Literal litSummary;
    protected global::System.Web.UI.WebControls.DropDownList ddlEntityType;
    protected global::System.Web.UI.WebControls.DropDownList ddlWorkflowStep;
    protected global::System.Web.UI.WebControls.DropDownList ddlPriority;
    protected global::System.Web.UI.WebControls.TextBox txtEntityId;
    protected global::System.Web.UI.WebControls.TextBox txtRequestTitle;
    protected global::System.Web.UI.WebControls.TextBox txtRequestDescription;
    protected global::System.Web.UI.WebControls.Button btnCreateRequest;
    protected global::System.Web.UI.WebControls.GridView gvRequests;
}
