//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
//     Changes to this file may be overwritten by Visual Studio.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class ProjectDetails
{
    protected global::System.Web.UI.WebControls.Content Content1;

    protected global::System.Web.UI.WebControls.Content Content2;

    protected global::System.Web.UI.WebControls.Literal litProjectName;

    protected global::System.Web.UI.WebControls.Literal litProjectMeta;

    protected global::System.Web.UI.WebControls.HyperLink lnkBack;

    protected global::System.Web.UI.WebControls.HyperLink lnkEdit;

    protected global::System.Web.UI.WebControls.Panel pnlMessage;

    protected global::System.Web.UI.WebControls.Literal litMessage;

    protected global::System.Web.UI.WebControls.Literal litBoreholePlanCount;

    protected global::System.Web.UI.WebControls.Literal litBoreholeCount;

    protected global::System.Web.UI.WebControls.Literal litSampleCount;

    protected global::System.Web.UI.WebControls.Literal litLabTestCount;

    protected global::System.Web.UI.WebControls.Literal litProjectCode;

    protected global::System.Web.UI.WebControls.Literal litClientName;

    protected global::System.Web.UI.WebControls.Literal litProjectType;

    protected global::System.Web.UI.WebControls.Literal litStructureType;

    protected global::System.Web.UI.WebControls.Literal litCity;

    protected global::System.Web.UI.WebControls.Literal litLocationName;

    protected global::System.Web.UI.WebControls.Literal litSiteArea;

    protected global::System.Web.UI.WebControls.Literal litFloors;

    protected global::System.Web.UI.WebControls.HyperLink lnkProjectBoreholes;

    protected global::System.Web.UI.WebControls.HyperLink lnkProjectBoreholeLog;

    protected global::System.Web.UI.WebControls.HyperLink lnkProjectSamples;

    protected global::System.Web.UI.WebControls.HyperLink lnkProjectSPT;

    protected global::System.Web.UI.WebControls.HyperLink lnkProjectGroundwater;

    protected global::System.Web.UI.WebControls.HyperLink lnkProjectLabResults;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectReports;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectInvestigationPlan;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectQuality;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectSiteMap;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectCrossSections;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectCalculations;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectDocuments;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectExport;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectDataExchange;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectGisCad;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectPrintableOutputs;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectApproval;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectFollowUp;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectRisks;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectKpis;

}
