//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class ProjectRiskRegister
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Content Content2;
    protected global::System.Web.UI.WebControls.HyperLink lnkDashboard;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.HiddenField hfRiskId;
    protected global::System.Web.UI.WebControls.DropDownList ddlProject;
    protected global::System.Web.UI.WebControls.TextBox txtRiskCode;
    protected global::System.Web.UI.WebControls.DropDownList ddlRiskCategory;
    protected global::System.Web.UI.WebControls.DropDownList ddlOwner;
    protected global::System.Web.UI.WebControls.TextBox txtRiskTitle;
    protected global::System.Web.UI.WebControls.TextBox txtRiskDescription;
    protected global::System.Web.UI.WebControls.DropDownList ddlProbability;
    protected global::System.Web.UI.WebControls.DropDownList ddlImpact;
    protected global::System.Web.UI.WebControls.TextBox txtDueDate;
    protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
    protected global::System.Web.UI.WebControls.TextBox txtMitigationPlan;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.Button btnClear;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterProject;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterRiskLevel;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    protected global::System.Web.UI.WebControls.Button btnLoad;
    protected global::System.Web.UI.WebControls.GridView gvRisks;
}
