//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
//     Changes to this file may be overwritten by Visual Studio.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Projects
{
    protected global::System.Web.UI.WebControls.Content Content1;

    protected global::System.Web.UI.WebControls.Content Content2;

    protected global::System.Web.UI.WebControls.Button btnNew;

    protected global::System.Web.UI.WebControls.Panel pnlMessage;

    protected global::System.Web.UI.WebControls.Literal litMessage;

    protected global::System.Web.UI.WebControls.Panel pnlForm;

    protected global::System.Web.UI.WebControls.Literal litFormTitle;

    protected global::System.Web.UI.WebControls.HiddenField hfProjectId;

    protected global::System.Web.UI.WebControls.TextBox txtProjectCode;

    protected global::System.Web.UI.WebControls.TextBox txtProjectName;

    protected global::System.Web.UI.WebControls.TextBox txtProjectNameEn;

    protected global::System.Web.UI.WebControls.TextBox txtClientName;

    protected global::System.Web.UI.WebControls.DropDownList ddlProjectType;

    protected global::System.Web.UI.WebControls.DropDownList ddlProjectStatus;

    protected global::System.Web.UI.WebControls.DropDownList ddlStructureType;

    protected global::System.Web.UI.WebControls.DropDownList ddlInvestigationStage;

    protected global::System.Web.UI.WebControls.TextBox txtCountry;

    protected global::System.Web.UI.WebControls.TextBox txtCity;

    protected global::System.Web.UI.WebControls.TextBox txtDistrict;

    protected global::System.Web.UI.WebControls.TextBox txtLocationName;

    protected global::System.Web.UI.WebControls.TextBox txtSiteAreaM2;

    protected global::System.Web.UI.WebControls.TextBox txtNumberOfFloors;

    protected global::System.Web.UI.WebControls.TextBox txtBasementCount;

    protected global::System.Web.UI.WebControls.TextBox txtProjectStartDate;

    protected global::System.Web.UI.WebControls.TextBox txtProjectEndDate;

    protected global::System.Web.UI.WebControls.CheckBox chkIsActive;

    protected global::System.Web.UI.WebControls.TextBox txtAddress;

    protected global::System.Web.UI.WebControls.TextBox txtScopeOfWork;

    protected global::System.Web.UI.WebControls.TextBox txtGeneralNotes;

    protected global::System.Web.UI.WebControls.Button btnSave;

    protected global::System.Web.UI.WebControls.Button btnCancel;

    protected global::System.Web.UI.WebControls.TextBox txtSearch;

    protected global::System.Web.UI.WebControls.Button btnSearch;

    protected global::System.Web.UI.WebControls.Button btnClearSearch;

    protected global::System.Web.UI.WebControls.GridView gvProjects;

}
