//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class QualityKpiDashboard
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Content Content2;
    protected global::System.Web.UI.WebControls.HyperLink lnkExecutive;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.DropDownList ddlProject;
    protected global::System.Web.UI.WebControls.Button btnGenerate;
    protected global::System.Web.UI.WebControls.Literal litAvgScore;
    protected global::System.Web.UI.WebControls.Literal litLowScoreCount;
    protected global::System.Web.UI.WebControls.Literal litOpenFollowUps;
    protected global::System.Web.UI.WebControls.Literal litHighRisks;
    protected global::System.Web.UI.WebControls.GridView gvKpis;
}
