//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by GeoSite Pro Sprint 4 tooling.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class ReportEditor
{
    protected global::System.Web.UI.WebControls.Literal litReportTitle;
    protected global::System.Web.UI.WebControls.Literal litReportMeta;
    protected global::System.Web.UI.WebControls.HyperLink lnkBack;
    protected global::System.Web.UI.WebControls.HyperLink lnkPrint;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.Button btnGenerateDefault;
    protected global::System.Web.UI.WebControls.Button btnAddSection;
    protected global::System.Web.UI.WebControls.Panel pnlSectionForm;
    protected global::System.Web.UI.WebControls.Literal litSectionFormTitle;
    protected global::System.Web.UI.WebControls.HiddenField hfSectionId;
    protected global::System.Web.UI.WebControls.DropDownList ddlSectionType;
    protected global::System.Web.UI.WebControls.TextBox txtSortOrder;
    protected global::System.Web.UI.WebControls.TextBox txtSectionTitle;
    protected global::System.Web.UI.WebControls.TextBox txtSectionContent;
    protected global::System.Web.UI.WebControls.CheckBox chkIsIncluded;
    protected global::System.Web.UI.WebControls.Button btnSaveSection;
    protected global::System.Web.UI.WebControls.Button btnCancelSection;
    protected global::System.Web.UI.WebControls.GridView gvSections;
}
