//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by GeoSite Pro Sprint 4 tooling.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class ReportPrint
{
    protected global::System.Web.UI.WebControls.HyperLink lnkBack;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.Literal litReportTitle;
    protected global::System.Web.UI.WebControls.Literal litReportMeta;
    protected global::System.Web.UI.WebControls.Literal litReportNo;
    protected global::System.Web.UI.WebControls.Literal litRevisionNo;
    protected global::System.Web.UI.WebControls.Literal litIssueDate;
    protected global::System.Web.UI.WebControls.Literal litPreparedBy;
    protected global::System.Web.UI.WebControls.Literal litReviewedBy;
    protected global::System.Web.UI.WebControls.Literal litApprovedBy;
    protected global::System.Web.UI.WebControls.Literal litProjectInfo;
    protected global::System.Web.UI.WebControls.Literal litExecutiveSummary;
    protected global::System.Web.UI.WebControls.Repeater rptSections;
    protected global::System.Web.UI.WebControls.GridView gvBoreholes;
    protected global::System.Web.UI.WebControls.GridView gvLayers;
    protected global::System.Web.UI.WebControls.GridView gvSPT;
    protected global::System.Web.UI.WebControls.GridView gvGroundwater;
    protected global::System.Web.UI.WebControls.GridView gvSamples;
    protected global::System.Web.UI.WebControls.GridView gvLabResults;
}
