//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by GeoSite Pro Sprint 4 tooling.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Reports
{
    protected global::System.Web.UI.WebControls.Button btnNew;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.Panel pnlForm;
    protected global::System.Web.UI.WebControls.Literal litFormTitle;
    protected global::System.Web.UI.WebControls.HiddenField hfReportId;
    protected global::System.Web.UI.WebControls.DropDownList ddlProject;
    protected global::System.Web.UI.WebControls.DropDownList ddlReportType;
    protected global::System.Web.UI.WebControls.DropDownList ddlReportStatus;
    protected global::System.Web.UI.WebControls.TextBox txtReportNo;
    protected global::System.Web.UI.WebControls.TextBox txtReportTitle;
    protected global::System.Web.UI.WebControls.TextBox txtIssueDate;
    protected global::System.Web.UI.WebControls.TextBox txtRevisionNo;
    protected global::System.Web.UI.WebControls.TextBox txtPreparedBy;
    protected global::System.Web.UI.WebControls.TextBox txtReviewedBy;
    protected global::System.Web.UI.WebControls.TextBox txtApprovedBy;
    protected global::System.Web.UI.WebControls.TextBox txtExecutiveSummary;
    protected global::System.Web.UI.WebControls.TextBox txtRecommendations;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.Button btnCancel;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterProject;
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    protected global::System.Web.UI.WebControls.Button btnSearch;
    protected global::System.Web.UI.WebControls.Button btnClearSearch;
    protected global::System.Web.UI.WebControls.GridView gvReports;
}
