//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by GeoSite Pro Sprint 5 tooling.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class RolePermissions
{
    protected global::System.Web.UI.WebControls.HyperLink lnkBackRoles;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.DropDownList ddlRole;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.GridView gvPermissions;
}
