//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by GeoSite Pro Sprint 5 tooling.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Roles
{
    protected global::System.Web.UI.WebControls.Button btnNew;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.Panel pnlForm;
    protected global::System.Web.UI.WebControls.Literal litFormTitle;
    protected global::System.Web.UI.WebControls.HiddenField hfRoleId;
    protected global::System.Web.UI.WebControls.TextBox txtRoleName;
    protected global::System.Web.UI.WebControls.CheckBox chkIsActive;
    protected global::System.Web.UI.WebControls.TextBox txtDescription;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.Button btnCancel;
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;
    protected global::System.Web.UI.WebControls.Button btnSearch;
    protected global::System.Web.UI.WebControls.Button btnClearSearch;
    protected global::System.Web.UI.WebControls.GridView gvRoles;
}
