//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Samples
{
    protected global::System.Web.UI.WebControls.Button btnNew;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.Panel pnlForm;
    protected global::System.Web.UI.WebControls.Literal litFormTitle;
    protected global::System.Web.UI.WebControls.HiddenField hfSampleId;
    protected global::System.Web.UI.WebControls.DropDownList ddlProject;
    protected global::System.Web.UI.WebControls.DropDownList ddlBorehole;
    protected global::System.Web.UI.WebControls.TextBox txtSampleCode;
    protected global::System.Web.UI.WebControls.DropDownList ddlSampleType;
    protected global::System.Web.UI.WebControls.TextBox txtFromDepthM;
    protected global::System.Web.UI.WebControls.TextBox txtToDepthM;
    protected global::System.Web.UI.WebControls.DropDownList ddlSampleQuality;
    protected global::System.Web.UI.WebControls.TextBox txtRecoveryLengthM;
    protected global::System.Web.UI.WebControls.TextBox txtTakenDate;
    protected global::System.Web.UI.WebControls.TextBox txtStorageLocation;
    protected global::System.Web.UI.WebControls.TextBox txtDescription;
    protected global::System.Web.UI.WebControls.TextBox txtRequiredTests;
    protected global::System.Web.UI.WebControls.TextBox txtNotes;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.Button btnCancel;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterProject;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterBorehole;
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    protected global::System.Web.UI.WebControls.Button btnSearch;
    protected global::System.Web.UI.WebControls.Button btnClearSearch;
    protected global::System.Web.UI.WebControls.GridView gvSamples;
}
