//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
//     Changes to this file may be overwritten by Visual Studio.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Site
{
    protected global::System.Web.UI.WebControls.ContentPlaceHolder TitleContent;
    protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
    protected global::System.Web.UI.WebControls.HyperLink lnkDashboard;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjects;
    protected global::System.Web.UI.WebControls.HyperLink lnkBoreholes;
    protected global::System.Web.UI.WebControls.HyperLink lnkBoreholeLog;
    protected global::System.Web.UI.WebControls.HyperLink lnkSamples;
    protected global::System.Web.UI.WebControls.HyperLink lnkSPTTests;
    protected global::System.Web.UI.WebControls.HyperLink lnkGroundwater;
    protected global::System.Web.UI.WebControls.HyperLink lnkLabResults;
    protected global::System.Web.UI.WebControls.HyperLink lnkReports;
    protected global::System.Web.UI.WebControls.HyperLink lnkStandards;
    protected global::System.Web.UI.WebControls.HyperLink lnkQualityChecks;
    protected global::System.Web.UI.WebControls.HyperLink lnkCalculations;
    protected global::System.Web.UI.WebControls.HyperLink lnkSiteMap;
    protected global::System.Web.UI.WebControls.HyperLink lnkCrossSections;
    protected global::System.Web.UI.WebControls.HyperLink lnkDataExchange;
    protected global::System.Web.UI.WebControls.HyperLink lnkGisCadExport;
    protected global::System.Web.UI.WebControls.HyperLink lnkPrintableOutputs;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectDocuments;
    protected global::System.Web.UI.WebControls.HyperLink lnkExportCenter;
    protected global::System.Web.UI.WebControls.HyperLink lnkInvestigationTemplates;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjectInvestigationPlan;
    protected global::System.Web.UI.WebControls.HyperLink lnkProductionReadiness;
    protected global::System.Web.UI.WebControls.HyperLink lnkUsers;
    protected global::System.Web.UI.WebControls.HyperLink lnkRoles;
    protected global::System.Web.UI.WebControls.HyperLink lnkRolePermissions;
    protected global::System.Web.UI.WebControls.HyperLink lnkAuditLog;
    protected global::System.Web.UI.WebControls.Literal litCurrentUser;
    protected global::System.Web.UI.WebControls.LinkButton btnLogout;
    protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
}
