//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
//     Changes to this file may be overwritten by Visual Studio.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class SiteVisit
{
    protected global::System.Web.UI.WebControls.Content Content1;

    protected global::System.Web.UI.WebControls.Content Content2;

}
