//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class SiteMapPage
{
    protected global::System.Web.UI.WebControls.HyperLink lnkCrossSections;
    protected global::System.Web.UI.WebControls.HyperLink lnkProjects;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.DropDownList ddlProject;
    protected global::System.Web.UI.WebControls.Button btnLoad;
    protected global::System.Web.UI.WebControls.Panel pnlProject;
    protected global::System.Web.UI.WebControls.Literal litProjectTitle;
    protected global::System.Web.UI.WebControls.Literal litProjectMeta;
    protected global::System.Web.UI.WebControls.Button btnGenerateActual;
    protected global::System.Web.UI.WebControls.Button btnGeneratePlan;
    protected global::System.Web.UI.WebControls.Literal litActualCount;
    protected global::System.Web.UI.WebControls.Literal litLayoutCount;
    protected global::System.Web.UI.WebControls.Literal litMissingCoordCount;
    protected global::System.Web.UI.WebControls.Panel pnlSettings;
    protected global::System.Web.UI.WebControls.TextBox txtCoordinateSystem;
    protected global::System.Web.UI.WebControls.TextBox txtEPSG;
    protected global::System.Web.UI.WebControls.TextBox txtOriginEasting;
    protected global::System.Web.UI.WebControls.TextBox txtOriginNorthing;
    protected global::System.Web.UI.WebControls.TextBox txtScaleDenominator;
    protected global::System.Web.UI.WebControls.TextBox txtNorthAngle;
    protected global::System.Web.UI.WebControls.TextBox txtBoundaryText;
    protected global::System.Web.UI.WebControls.TextBox txtMapNotes;
    protected global::System.Web.UI.WebControls.Button btnSaveSettings;
    protected global::System.Web.UI.WebControls.Panel pnlMap;
    protected global::System.Web.UI.WebControls.Literal litMapSvg;
    protected global::System.Web.UI.WebControls.Panel pnlAddPoint;
    protected global::System.Web.UI.WebControls.HiddenField hfPointId;
    protected global::System.Web.UI.WebControls.TextBox txtPointCode;
    protected global::System.Web.UI.WebControls.DropDownList ddlPointSource;
    protected global::System.Web.UI.WebControls.TextBox txtPointEasting;
    protected global::System.Web.UI.WebControls.TextBox txtPointNorthing;
    protected global::System.Web.UI.WebControls.TextBox txtPointElevation;
    protected global::System.Web.UI.WebControls.TextBox txtPointDepth;
    protected global::System.Web.UI.WebControls.TextBox txtPointNotes;
    protected global::System.Web.UI.WebControls.Button btnSavePoint;
    protected global::System.Web.UI.WebControls.Button btnClearPoint;
    protected global::System.Web.UI.WebControls.Panel pnlPoints;
    protected global::System.Web.UI.WebControls.GridView gvPoints;
}
