//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class SPTTests
{
    protected global::System.Web.UI.WebControls.Button btnNew;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.Panel pnlForm;
    protected global::System.Web.UI.WebControls.Literal litFormTitle;
    protected global::System.Web.UI.WebControls.HiddenField hfSPTTestId;
    protected global::System.Web.UI.WebControls.DropDownList ddlProject;
    protected global::System.Web.UI.WebControls.DropDownList ddlBorehole;
    protected global::System.Web.UI.WebControls.TextBox txtTestDepthM;
    protected global::System.Web.UI.WebControls.TextBox txtTestDate;
    protected global::System.Web.UI.WebControls.TextBox txtBlowCount1;
    protected global::System.Web.UI.WebControls.TextBox txtBlowCount2;
    protected global::System.Web.UI.WebControls.TextBox txtBlowCount3;
    protected global::System.Web.UI.WebControls.TextBox txtNValue;
    protected global::System.Web.UI.WebControls.TextBox txtHammerEnergyRatio;
    protected global::System.Web.UI.WebControls.TextBox txtCorrectedN;
    protected global::System.Web.UI.WebControls.TextBox txtRecoveryLengthM;
    protected global::System.Web.UI.WebControls.TextBox txtNotes;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.Button btnCancel;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterProject;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterBorehole;
    protected global::System.Web.UI.WebControls.Button btnClearSearch;
    protected global::System.Web.UI.WebControls.GridView gvSPTTests;
}
