//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class SystemHealth
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Content Content2;
    protected global::System.Web.UI.WebControls.Button btnRefresh;
    protected global::System.Web.UI.WebControls.Button btnLogHealthCheck;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.Literal litRequiredTables;
    protected global::System.Web.UI.WebControls.Literal litMissingTables;
    protected global::System.Web.UI.WebControls.Literal litActiveSettings;
    protected global::System.Web.UI.WebControls.Literal litBackupJobs;
    protected global::System.Web.UI.WebControls.GridView gvHealthChecks;
}
