//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class SystemSettings
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Content Content2;
    protected global::System.Web.UI.WebControls.Button btnNew;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.HiddenField hfSettingId;
    protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
    protected global::System.Web.UI.WebControls.TextBox txtSettingKey;
    protected global::System.Web.UI.WebControls.DropDownList ddlDataType;
    protected global::System.Web.UI.WebControls.TextBox txtSettingValue;
    protected global::System.Web.UI.WebControls.TextBox txtDescription;
    protected global::System.Web.UI.WebControls.CheckBox chkIsEncrypted;
    protected global::System.Web.UI.WebControls.CheckBox chkIsActive;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.Button btnClear;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterCategory;
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    protected global::System.Web.UI.WebControls.Button btnSearch;
    protected global::System.Web.UI.WebControls.GridView gvSettings;
}
