//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by GeoSite Pro Sprint 5 tooling.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Users
{
    protected global::System.Web.UI.WebControls.Button btnNew;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.Panel pnlForm;
    protected global::System.Web.UI.WebControls.Literal litFormTitle;
    protected global::System.Web.UI.WebControls.HiddenField hfUserId;
    protected global::System.Web.UI.WebControls.TextBox txtUsername;
    protected global::System.Web.UI.WebControls.TextBox txtFullName;
    protected global::System.Web.UI.WebControls.TextBox txtEmail;
    protected global::System.Web.UI.WebControls.TextBox txtMobile;
    protected global::System.Web.UI.WebControls.Literal litPasswordHint;
    protected global::System.Web.UI.WebControls.TextBox txtPassword;
    protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
    protected global::System.Web.UI.WebControls.CheckBox chkIsActive;
    protected global::System.Web.UI.WebControls.CheckBoxList cblRoles;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.Button btnCancel;
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;
    protected global::System.Web.UI.WebControls.Button btnSearch;
    protected global::System.Web.UI.WebControls.Button btnClearSearch;
    protected global::System.Web.UI.WebControls.GridView gvUsers;
}
