//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated to support the ASP.NET Web Application build.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class WorkflowInbox
{
    protected global::System.Web.UI.WebControls.Content Content1;
    protected global::System.Web.UI.WebControls.Content Content2;
    protected global::System.Web.UI.WebControls.Panel pnlMessage;
    protected global::System.Web.UI.WebControls.Literal litMessage;
    protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
    protected global::System.Web.UI.WebControls.TextBox txtSearch;
    protected global::System.Web.UI.WebControls.Button btnLoad;
    protected global::System.Web.UI.WebControls.Button btnPending;
    protected global::System.Web.UI.WebControls.GridView gvInbox;
}
